service: meal-scheduler

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: sa-east-1
  memorySize: 256
  stage: ${env:ENV}
  deploymentBucket:
    name: em-serverless
    tags:
      Service: IHC
  environment:
    ENV: ${env:ENV}
    RUN_MIGRATION: ${env:RUN_MIGRATION}
    PG_HOST: ${env:PG_HOST}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}
    PG_DATABASE: ${env:PG_DATABASE}
      
package:
  individually: true
  include:
    - ormconfig.js
    
functions: 
  - ${file(./start/routes/establishment.routes.yml)}

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-offline
