service: meal-scheduler

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: sa-east-1
  memorySize: 512
  timeout: 30
  stage: ${env:ENV}
  deploymentBucket:
    name: em-serverless
    tags:
      Service: IHC
  environment:
    ENV: ${env:ENV}
    PG_HOST: ${env:PG_HOST}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}
    PG_DATABASE: ${env:PG_DATABASE}
    REMOTE: ${env:REMOTE}
          
package:
  individually: true
    
functions:
  - ${file(./start/routes/establishment.routes.yml)}
  - ${file(./start/routes/environment.routes.yml)}
  - ${file(./start/routes/menuitem.routes.yml)}
  - ${file(./start/routes/table.routes.yml)}
  - ${file(./start/routes/reservation.routes.yml)}
  - ${file(./start/routes/schedule.routes.yml)}
  - ${file(./start/routes/user.routes.yml)}

custom:
  customDomain:
    domainName: ${env:ENV}-serverless.evshosting.net
    certificateName: 'evshosting.net'
    hostedZoneId: ZCMLWB8V5SYIT
    endpointType: regional
    createRoute53Record: true
    autoDomain: true
  serverless-offline:
    host: 0.0.0.0
    port: 3000

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-offline
  - serverless-domain-manager

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'