service: meal-scheduler

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: sa-east-1
  memorySize: 256
  deploymentBucket:
    name: em-serverless
    tags:
      Service: IHC

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript