service: meal-scheduler

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: sa-east-1
  memorySize: 256
  deploymentBucket:
    name: em-serverless
    tags:
      Service: IHC
      
package:
  individually: true

functions:
  hello:
    handler: router.establishmentCreate
    events:
      - http:
          path: /establishment/create
          method: post

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-offline
