environmentCreate:
  handler: ./start/router.environmentCreate
  events:
    - http:
        path: /environment/create
        method: post
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request

environmentLoad:
  handler: ./start/router.environmentLoad
  events:
    - http:
        path: /environment/load
        method: get
        cors: true
    - http:
        path: /environment/load/{id}
        method: get
        cors: true

environmentDelete:
  handler: ./start/router.environmentDelete
  events:
    - http:
        path: /environment/delete/{id}
        method: delete
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request

environmentUpdate:
  handler: ./start/router.environmentUpdate
  events:
    - http:
        path: /environment/update/{id}
        method: put
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request