environmentCreate:
  handler: ./start/router.environmentCreate
  events:
    - http:
        path: /environment/create
        method: post
        authorizer: 
          name: basicAuthorizer
          type: request

environmentLoad:
  handler: ./start/router.environmentLoad
  events:
    - http:
        path: /environment/load/{id?}
        method: get

environmentDelete:
  handler: ./start/router.environmentDelete
  events:
    - http:
        path: /environment/delete/{id}
        method: delete
        authorizer: 
          name: basicAuthorizer
          type: request

environmentUpdate:
  handler: ./start/router.environmentUpdate
  events:
    - http:
        path: /environment/update/{id}
        method: put
        authorizer: 
          name: basicAuthorizer
          type: request