establishmentCreate:
  handler: ./start/router.establishmentCreate
  events:
    - http:
        path: /establishment/create
        method: post

establishmentLoad:
  handler: ./start/router.establishmentLoad
  events:
    - http:
        path: /establishment/load/{id?}
        method: get

establishmentDelete:
  handler: ./start/router.establishmentDelete
  events:
    - http:
        path: /establishment/delete/{id}
        method: delete

establishmentUpdate:
  handler: ./start/router.establishmentUpdate
  events:
    - http:
        path: /establishment/update/{id}
        method: put