establishmentCreate:
  handler: ./start/router.establishmentCreate
  events:
    - http:
        path: /establishment/create
        method: post
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request

establishmentLoad:
  handler: ./start/router.establishmentLoad
  events:
    - http:
        path: /establishment/load
        method: get
        cors: true
    - http:
        path: /establishment/load/{id}
        method: get

establishmentDelete:
  handler: ./start/router.establishmentDelete
  events:
    - http:
        path: /establishment/delete/{id}
        method: delete
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request

establishmentUpdate:
  handler: ./start/router.establishmentUpdate
  events:
    - http:
        path: /establishment/update/{id}
        method: put
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request