menuCreate:
  handler: ./start/router.menuCreate
  events:
    - http:
        path: /menu/create
        method: post
        authorizer: 
          name: basicAuthorizer
          type: request

menuLoad:
  handler: ./start/router.menuLoad
  events:
    - http:
        path: /menu/load
        method: get
    - http:
        path: /menu/load/{id}
        method: get

menuDelete:
  handler: ./start/router.menuDelete
  events:
    - http:
        path: /menu/delete/{id}
        method: delete
        authorizer: 
          name: basicAuthorizer
          type: request

menuUpdate:
  handler: ./start/router.menuUpdate
  events:
    - http:
        path: /menu/update/{id}
        method: put
        authorizer: 
          name: basicAuthorizer
          type: request