menuCreate:
  handler: ./start/router.menuCreate
  events:
    - http:
        path: /menu/create
        method: post
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request

menuLoad:
  handler: ./start/router.menuLoad
  events:
    - http:
        path: /menu/load
        method: get
        cors: true
    - http:
        path: /menu/load/{id}
        method: get
        cors: true

menuDelete:
  handler: ./start/router.menuDelete
  events:
    - http:
        path: /menu/delete/{id}
        method: delete
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request

menuUpdate:
  handler: ./start/router.menuUpdate
  events:
    - http:
        path: /menu/update/{id}
        method: put
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request