reservationCreate:
  handler: ./start/router.reservationCreate
  events:
    - http:
        path: /reservation/create
        method: post

reservationLoad:
  handler: ./start/router.reservationLoad
  events:
    - http:
        path: /reservation/load/{id?}
        method: get

reservationDelete:
  handler: ./start/router.reservationDelete
  events:
    - http:
        path: /reservation/delete/{id}
        method: delete

reservationUpdate:
  handler: ./start/router.reservationUpdate
  events:
    - http:
        path: /reservation/update/{id}
        method: put