reservationCreate:
  handler: ./start/router.reservationCreate
  events:
    - http:
        path: /reservation/create
        method: post

reservationLoad:
  handler: ./start/router.reservationLoad
  events:
    - http:
        path: /reservation/load
        method: get
        authorizer: 
          name: basicAuthorizer
          type: request
    - http:
        path: /reservation/load/{id}
        method: get
        authorizer: 
          name: basicAuthorizer
          type: request

reservationUpdate:
  handler: ./start/router.reservationUpdate
  events:
    - http:
        path: /reservation/update/{id}
        method: put
        authorizer: 
          name: basicAuthorizer
          type: request

reservationSafeLoad:
  handler: ./start/router.reservationSafeLoad
  events:
    - http:
        path: /reservation/safeLoad
        method: get