reservationCreate:
  handler: ./start/router.reservationCreate
  events:
    - http:
        path: /reservation/create
        method: post
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true

reservationLoad:
  handler: ./start/router.reservationLoad
  events:
    - http:
        path: /reservation/load
        method: get
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true
        authorizer: 
          name: basicAuthorizer
          type: request
    - http:
        path: /reservation/load/{id}
        method: get
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true
        authorizer: 
          name: basicAuthorizer
          type: request

reservationUpdate:
  handler: ./start/router.reservationUpdate
  events:
    - http:
        path: /reservation/update/{id}
        method: put
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true
        authorizer: 
          name: basicAuthorizer
          type: request

reservationSafeLoad:
  handler: ./start/router.reservationSafeLoad
  events:
    - http:
        path: /reservation/safeLoad
        method: get
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true

reservationSafeUpdate:
  handler: ./start/router.reservationSafeUpdate
  events:
    - http:
        path: /reservation/safeUpdate/{id}
        method: put
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true