scheduleCreate:
  handler: ./start/router.scheduleCreate
  events:
    - http:
        path: /schedule/create
        method: post
        authorizer: 
          name: basicAuthorizer
          type: request

scheduleLoad:
  handler: ./start/router.scheduleLoad
  events:
    - http:
        path: /schedule/load/{id?}
        method: get

scheduleDelete:
  handler: ./start/router.scheduleDelete
  events:
    - http:
        path: /schedule/delete/{id}
        method: delete
        authorizer: 
          name: basicAuthorizer
          type: request

scheduleUpdate:
  handler: ./start/router.scheduleUpdate
  events:
    - http:
        path: /schedule/update/{id}
        method: put
        authorizer: 
          name: basicAuthorizer
          type: request