scheduleCreate:
  handler: ./start/router.scheduleCreate
  events:
    - http:
        path: /schedule/create
        method: post
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request

scheduleLoad:
  handler: ./start/router.scheduleLoad
  events:
    - http:
        path: /schedule/load
        method: get
        cors: true
    - http:
        path: /schedule/load/{id}
        method: get
        cors: true

scheduleDelete:
  handler: ./start/router.scheduleDelete
  events:
    - http:
        path: /schedule/delete/{id}
        method: delete
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request

scheduleUpdate:
  handler: ./start/router.scheduleUpdate
  events:
    - http:
        path: /schedule/update/{id}
        method: put
        cors: true
        authorizer: 
          name: basicAuthorizer
          type: request