tableCreate:
  handler: ./start/router.tableCreate
  events:
    - http:
        path: /table/create
        method: post
        authorizer: 
          name: basicAuthorizer
          type: request

tableLoad:
  handler: ./start/router.tableLoad
  events:
    - http:
        path: /table/load/{id?}
        method: get

tableDelete:
  handler: ./start/router.tableDelete
  events:
    - http:
        path: /table/delete/{id}
        method: delete
        authorizer: 
          name: basicAuthorizer
          type: request

tableUpdate:
  handler: ./start/router.tableUpdate
  events:
    - http:
        path: /table/update/{id}
        method: put
        authorizer: 
          name: basicAuthorizer
          type: request