tableCreate:
  handler: ./start/router.tableCreate
  events:
    - http:
        path: /table/create
        method: post
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true
        authorizer: 
          name: basicAuthorizer
          type: request

tableLoad:
  handler: ./start/router.tableLoad
  events:
    - http:
        path: /table/load
        method: get
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true
    - http:
        path: /table/load/{id}
        method: get
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true

tableDelete:
  handler: ./start/router.tableDelete
  events:
    - http:
        path: /table/delete/{id}
        method: delete
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true
        authorizer: 
          name: basicAuthorizer
          type: request

tableUpdate:
  handler: ./start/router.tableUpdate
  events:
    - http:
        path: /table/update/{id}
        method: put
        cors:
          origin: '*'
          headers: '*'
          allowCredentials: true
        authorizer: 
          name: basicAuthorizer
          type: request