name: Manual serverless

on: 
  workflow_dispatch:
    inputs:
      method: 
        description: "Code to complement serverless command"
        required: true

jobs:
    manual:
      
      runs-on: ubuntu-latest
      container:  node:lts-alpine

      steps:
        - name: Check out repository code
          uses: actions/checkout@v2
   
        - name: Install dependencies
          run: yarn
      
        - name: Serverless command
          uses: serverless/github-action@master
          with:
            args: ${{ github.event.inputs.method }}
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
