name: Pull Request

on: pull_request

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:14

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgresihc
          POSTGRES_USER: postgres
          POSTGRES_DB: meal-scheduler-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn coverage
        env:
          ENV: test
          PG_HOST: postgres
          PG_USERNAME: postgres
          PG_PASSWORD: postgresihc
          PG_DATABASE: meal-scheduler